language:
  - cpp
  - python

before_script:
    - mkdir build
    - cd build
    - cmake -DQT_VARIANT="qt5" -DUSE_TESTS=True ..
    - cd ..

script:
    - make -k -j2 VERBOSE=1 -C build
    - ctest --output-on-failure