#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language:
  - cpp
  - python

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - ubuntu-sdk-team
    packages:
    - g++-4.8
    - cmake
    - libqt4-dev

env:
- COMPILER_VERSION=4.8

before_script:
  - mkdir build
  - cd build
  - CC=$CC-${COMPILER_VERSION} CXX=$CXX-${COMPILER_VERSION} cmake -DQT_VARIANT="qt4" -DUSE_TESTS=True ..
  - cd ..

script:
  - cd build
  - make -k -j2 VERBOSE=1
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ctest --output-on-failure
