dist: trusty
sudo: false

language:
  - cpp
  - python

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - ubuntu-sdk-team
    packages:
    - g++-4.8
    - cmake
    - libqt4-dev

env:
- COMPILER_VERSION=4.8

before_script:
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install qt5;
      export PATH=`brew --prefix qt5`/bin:${PATH};
      ls /opt/;
      cmake -DQT_VARIANT="qt5" -DUSE_TESTS=True ..;
    else
      export CC=$CC-${COMPILER_VERSION};
      export CXX=$CXX-${COMPILER_VERSION};
      cmake -DQT_VARIANT="qt4" -DUSE_TESTS=True ..;
    fi
  - cd ..

script:
  - cd build
  - make -k -j2 VERBOSE=1
  # one gui test failed for some reason, need find some time to reboot to macos and debug
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
      ctest --output-on-failure;
    else
      ctest --output-on-failure  -I 1,2,1;
    fi  
